# Generated by Django 6.0.6 on 2026-06-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
