# Generated by Django 6.0.6 on 2026-06-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_movie_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
