# Generated by Django 6.0.6 on 2026-06-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
