# Generated by Django 6.0.6 on 2026-06-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="web_site",
            field=models.URLField(blank=True, null=True),
        ),
    ]
