# Generated by Django 6.0.6 on 2026-06-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_phone_number_user_web_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
    ]
