# Generated by Django 6.0.6 on 2026-06-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_instagram_user_linkedin_user_twitter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="instagram",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="linkedin",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="twitter",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="web_site",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
