# Generated by Django 6.0.6 on 2026-06-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
