# Generated by Django 6.0.6 on 2026-06-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
